###
POST https://server-13t5.onrender.com/api/user/signup
Content-Type: application/json

{
  "name": "Admin User",
  "phone": "9876543210",
  "email": "admin@example.com",
  "password": "AdminPass123"
}

###
POST https://server-13t5.onrender.com/api/user/signin
Content-Type: application/json

{
  "phone": "9876543210",
  "password": "123456"
}



