###
POST http://localhost:8000/api/user/admin/signup
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNyaWJhYnVtYW5kcmFqdUBnbWFpbC5jb20iLCJpZCI6IjY3NGMyYzk3YTY3MDkxMDc5MDYyY2UxNCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTczNjQ0NzI1Mn0.RdD6-dMesr8psz5bv8hSdvwI6FED7dHB913oQGVi_mw

{
  "name": "Admin User",
  "phone": "1234567890",
  "email": "admin@example.com",
  "password": "AdminPass123"
}


###
POST http://localhost:8000/api/user/admin/signin
Content-Type: application/json

{
  "email": "sribabumandraju@gmail.com",
  "password": "123456"
}

###
GET http://localhost:8000/api/user
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNyaWJhYnVtYW5kcmFqdUBnbWFpbC5jb20iLCJpZCI6IjY3NGMyYzk3YTY3MDkxMDc5MDYyY2UxNCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTczNjQ0NzI1Mn0.RdD6-dMesr8psz5bv8hSdvwI6FED7dHB913oQGVi_mw



###
GET http://localhost:8000/api/user/
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNyaWJhYnVtYW5kcmFqdUBnbWFpbC5jb20iLCJpZCI6IjY3NGMyYzk3YTY3MDkxMDc5MDYyY2UxNCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTczNjQ0NzI1Mn0.RdD6-dMesr8psz5bv8hSdvwI6FED7dHB913oQGVi_mw


###
POST http://localhost:8000/api/user/verifyAccount/resendOtp
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNyaWJhYnVtYW5kcmFqdUBnbWFpbC5jb20iLCJpZCI6IjY3NGMyYzk3YTY3MDkxMDc5MDYyY2UxNCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTczNjQ0NzI1Mn0.RdD6-dMesr8psz5bv8hSdvwI6FED7dHB913oQGVi_mw


{
  "email": "sribabumandraju@gmail.com"
}



###
PUT http://localhost:8000/api/user/verifyAccount/emailVerify/674c2c97a67091079062ce14
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNyaWJhYnVtYW5kcmFqdUBnbWFpbC5jb20iLCJpZCI6IjY3NGMyYzk3YTY3MDkxMDc5MDYyY2UxNCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTczNjQ0NzI1Mn0.RdD6-dMesr8psz5bv8hSdvwI6FED7dHB913oQGVi_mw


{
  "email": "sribabumandraju@gmail.com",
  "otp": "399698"
}



###
POST http://localhost:8000/api/user/verifyemail
Content-Type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNyaWJhYnVtYW5kcmFqdUBnbWFpbC5jb20iLCJpZCI6IjY3NGMyYzk3YTY3MDkxMDc5MDYyY2UxNCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTczNjQ0NzI1Mn0.RdD6-dMesr8psz5bv8hSdvwI6FED7dHB913oQGVi_mw


{
  "email": "sribabumandraju@gmail.com",
  "otp": "898571"
}







